_partial_: True
_target_: disentangle.models.InfoGAN
encoder_partial: ???
latent_partial:
  _partial_: True
  _target_: disentangle.latents.UniformLatent
  num_latents: ???
decoder_partial: ???
lambdas:
  gradient: 10
  latent: 0.  # must be zero!
  value: 1
  l2: 0.