params:
  model_partial: quantized_ae
  encoder_partial: image
  decoder_partial: style_image
  data.name: falcor3d
  model_partial.latent_partial.num_latents: twice_sources
  model_partial.latent_partial.num_values_per_latent: 10
  model_partial.lambdas.quantization: 0.01
  model_partial.lambdas.commitment: 0.01
  model_partial.lambdas.l2: 0.1
  model_partial.lambdas.l1: 0.
  experiment.seed: 101
  optim.num_steps: 2e5
