_partial_: True
_target_: disentangle.models.VQVAE
encoder_partial: ???
latent_partial:
  _partial_: True
  _target_: disentangle.latents.VectorQuantizedLatent
  num_latents: ???
  num_embeddings: 512
  embedding_size: 64
decoder_partial: ???
lambdas:
  binary_cross_entropy: 1.
  quantization: 1.
  commitment: 0.25
  l2: 0