_partial_: True
_target_: disentangle.decoders.StyleImageDecoder
dense_partial:
  _partial_: True
  _target_: disentangle.blocks.DenseBlocks
  widths: [ 512 ]
  activation: relu
  norm: none
style_conv_transpose_partial:
  _partial_: True
  _target_: disentangle.blocks.StyleConvTranspose2DBlocks
  widths: [ 512, 256, 128, 64 ]
  kernel_sizes: [ 4, 4, 4, 4 ]
  strides: [ 2, 2, 2, 2 ]
  paddings: [ 1, 1, 1, 1 ]
  activation: leaky_relu
  norm: none
conv_partial:
  _partial_: True
  _target_: disentangle.blocks.Conv2DBlock
  kernel_size: 3
  stride: 1
  padding: 1
  norm: none
  activation: none
input_channels: 512
