params:
  model_partial: vqvae
  encoder_partial: image
  decoder_partial: style_image
  data.name: isaac3d
  model_partial.latent_partial.num_latents: twice_sources
  model_partial.latent_partial.num_embeddings: 512
  model_partial.latent_partial.embedding_size: 64
  model_partial.lambdas.quantization: 1.
  model_partial.lambdas.commitment: 0.25
  model_partial.lambdas.l2: 0.01
  experiment.seed: 101
  optim.num_steps: 2e5